<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied!' => '',
    'Anonymous poll!' => '',
    'Could not load poll!' => 'Non posso caricare il sondaggio!',
    'Invalid answer!' => 'Risposta non valida!',
    'Users voted for: <strong>{answer}</strong>' => 'Gli utenti hanno votato per: <strong>{answer}</strong>',
    'Voting for multiple answers is disabled!' => 'Il voto per risposte multiple è disabilitato!',
    'You have insufficient permissions to perform that operation!' => 'Non hai i permessi sufficienti per eseguire questa operazione!',
];
