<?php
/**
 * Translation: Paul (https://paul.bid) paulbid@protonmail.com
 */
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Edit your poll question...' => 'Отредактируйте свой вопрос для опроса...',
    'Hide results until poll is closed?' => 'Скрыть результаты, пока опрос не будет завершён?',
    'Add answer...' => 'Добавить ответ...',
    'Anonymous Votes?' => 'Опрос анонимный?',
    'Ask something...' => 'Спросите о чём нибудь...',
    'Display answers in random order?' => 'Показывать ответы в случайном порядке?',
    'Edit answer (empty answers will be removed)...' => 'Редактировать ответ (пустые ответы будут удалены)...',
];
