<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>There are no polls yet!</b>' => '<b>目前还没有投票!</b>',
    '<b>There are no polls yet!</b><br>Be the first and create one...' => '<b>目前还没有投票!</b><br>第一个发起投票...',
    'Asked by me' => '我提的问题',
    'No answered yet' => '还没有回答',
    'Only private polls' => '仅私有投票',
    'Only public polls' => '仅公共投票',
];
