<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Again? ;Weary;' => 'Encore ? ;Weary;',
    'Club A Steakhouse' => 'Hippopotamus',
    'Pisillo Italian Panini' => 'Panini chez Pisillo',
    'Right now, we are in the planning stages for our next meetup and we would like to know from you, where you would like to go?' => 
    'Nous sommes en train de préparer notre prochaine rencontre, et nous voudrions savoir où vous aimeriez aller ?',
    'To Daniel' => 'Chez Daniel',
    'Why don\'t we go to Bemelmans Bar?' => 'Pourquoi on n\'irait pas au bar Bemelmans ?',
];
