<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Note:</strong> The result is hidden until the poll is closed by a moderator.' => '<strong>Nota:</ strong> O resultado ficará oculto até que a votação seja fechada por um moderador.',
  'Anonymous' => 'Anônimo',
  'Closed' => 'Fechada',
  'Complete Poll' => 'Completar Enquete',
  'Reopen Poll' => 'Reabrir Enquete',
  'Reset my vote' => 'Redefinir meu voto',
  'Vote' => 'Votar',
  'and {count} more vote for this.' => 'e mais {count} votos para este.',
  'votes' => 'votos',
  'Created at' => '',
  'Export poll' => '',
);
