<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Anonymous' => '匿名',
    'Closed' => '关闭',
    'Complete Poll' => '完成投票',
    'Reopen Poll' => '重新打开投票',
    'Reset my vote' => '重置我的投票',
    'Vote' => '投票',
    'and {count} more vote for this.' => '另外 {count} 个投票。',
    'votes' => '票',
];
