<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<b>There are no polls yet!</b><br>Be the first and create one...' => '',
  'Filter' => '',
  'Asked by me' => 'Preguntat per mi',
  'Creation time' => 'Creat',
  'Display all' => 'Veure tot',
  'Last update' => 'Última actualització',
  'No answered yet' => 'No contestat',
  'No poll found which matches your current filter(s)!' => 'No s\'han trobat enquestes que coincideixin amb aquests criteris!',
  'Only private polls' => 'Només enquestes privades',
  'Only public polls' => 'Només enquestes públiques',
  'Sorting' => 'Ordenació',
);
