<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied!' => '',
    'Anonymous poll!' => '',
    'Could not load poll!' => 'نظرسنجی بارگذاری نشد!',
    'Invalid answer!' => 'پاسخ نامعتبر!',
    'Users voted for: <strong>{answer}</strong>' => 'کاربران به <strong>{answer}</strong> رای دادند',
    'Voting for multiple answers is disabled!' => 'رای‌دادن به چند پاسخ غیرفعال است!',
    'You have insufficient permissions to perform that operation!' => 'شما  مجاز به انجام عملیات نیستید!',
];
