<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hide results until poll is closed?' => '',
    'Add answer...' => 'Thêm câu trả lời...',
    'Anonymous Votes?' => 'Cho phép biểu quyết nặc danh?',
    'Ask something...' => 'Hỏi gì đó...',
    'Display answers in random order?' => 'Hiển thị câu trả lời theo thứ tự ngẫu nhiên?',
    'Edit answer (empty answers will be removed)...' => 'Chỉnh sửa câu hỏi (câu hỏi trống sẽ bị xóa bỏ)...',
    'Edit your poll question...' => 'Chỉnh sửa câu hỏi biểu quyết...',
];
