<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hide results until poll is closed?' => '',
    'Add answer...' => 'Pievieno atbildi...',
    'Anonymous Votes?' => 'Anonīmi balsojumi?',
    'Ask something...' => 'Pavaicā kaut ko...',
    'Display answers in random order?' => 'Parādīt atbildes jauktā kārtībā?',
    'Edit answer (empty answers will be removed)...' => 'Labot atbildi (tukšie balsojumi tiks dzēsti)...',
    'Edit your poll question...' => 'Labot savu aptaujas jautājumu...',
];
