<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Note:</strong> The result is hidden until the poll is closed by a moderator.' => '',
    'Anonymous' => 'Anonīma',
    'Closed' => 'Slēgta',
    'Complete Poll' => 'Pabeigt aptauju',
    'Reopen Poll' => 'Atkal atvērt aptauju',
    'Reset my vote' => 'Atcelt manu balsojumu',
    'Vote' => 'Balsot',
    'and {count} more vote for this.' => 'un vēl {count} citi balsoja par šo.',
    'votes' => 'balsis',
];
