name: PHP Codeception Tests - develop

on:
  push:
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-develop-new.yml@main
    with:
      module-id: polls
      use-rest-module: true
